--- #YAML:1.0
name:                File-Find-Parallel
version:             v0.0.2
abstract:            Traverse a number of similar directories in parallel
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    File::Tempdir:                 0.02
    Getopt::Long:                  2.34
    Pod::Usage:                    1.3
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Armstrong <andy@hexten.net>
